Improve deployment
This change uses GitHub deployments API to perform the deployment.

diff --git a/files/omegaup-uprev b/files/omegaup-uprev
--- a/files/omegaup-uprev
+++ b/files/omegaup-uprev
@@ -12,11 +12,15 @@ YARN=node_modules/yarn/bin/yarn
 sudo -u omegaup-www -i /bin/bash -c \
 	"set -e;
    cd \"${STAGING}\";
+   rm -rf \"${STAGING}/${JS_DIST}\";
+   mkdir -p \"${STAGING}/${JS_DIST}\";
+   COMMIT=\$(git rev-parse HEAD);
+   curl \"https://s3.amazonaws.com/omegaup-build-artifacts/webpack-artifacts/\${COMMIT}.tar.xz\" | \\
+     tar -xJ -C \"${STAGING}/${JS_DIST}\" && exit 0 || echo \"Prebuilt not found. Building locally\";
    . /opt/nvm/nvm.sh;
    if [ \$(nvm current) = \"none\" ]; then
      nvm install node;
    fi;
    npm ls --parseable -g yarn > /dev/null || npm install -g yarn;
    yarn install;
-   rm -rf \"${STAGING}/${JS_DIST}\";
    yarn run build"
